export const skills = [
  { name: "React.Js", level: "Intermediate" },
  { name: "Next.Js", level: "Intermediate" },
  { name: "HTML", level: "Intermediate" },
  { name: "CSS", level: "Intermediate" },
  { name: "Javascript", level: "Intermediate" },
  { name: "Typescript", level: "Intermediate" },
  { name: "React Query", level: "Intermediate" },
  { name: "Vue.Js", level: "Beginner" },
  { name: "Tailwindcss", level: "Intermediate" },
  { name: "Redux", level: "Intermediate" },
  { name: "Node", level: "Intermediate" },
  { name: "Jest", level: "Beginner" },
  { name: "Github", level: "Intermediate" },
  { name: "Sass", level: "Intermediate" },
  { name: "Framer", level: "Beginner" },
  { name: "Npm", level: "Intermediate" },
  { name: "Yarn", level: "Intermediate" },
];
